import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import { FlatCompat } from '@eslint/eslintrc';
import nextPlugin from '@next/eslint-plugin-next';

/**
 * Lint config for the whole monorepo (OPS-13).
 *
 * `npm run lint` had never run: the script was `eslint src --ext .ts` and
 * eslint was not installed anywhere, so it exited 127 and every "lint passed"
 * in this repo's history meant "lint did not execute". That is also why the
 * tenant-scoping guard from SEC-04 lives in the jest suite — a lint rule would
 * have been the natural home and there was nowhere to put one.
 *
 * The rule set is deliberately close to the recommended baselines. A first run
 * on a codebase this size surfaces a backlog, and the useful question is which
 * violations point at real defects, not how many can be silenced. Rules that
 * fire on the existing style without indicating a bug are set to `warn` so
 * they are visible and non-blocking; anything that has actually hidden a
 * defect in this codebase is an `error`.
 */
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'apps/api/prisma/seeds/**',
      'netlify/**',
      'tools/**',
      // Generated by Next on every build; its triple-slash reference is not
      // ours to restyle.
      'apps/web/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  /**
   * Build config and standalone Node scripts are CommonJS run by Node, not
   * application source. Without this they produce 21 `no-undef` errors for
   * `module` and `require` — noise that would have buried the real findings on
   * the first run.
   *
   * Placed *after* the recommended sets on purpose: flat config resolves last
   * match wins, so putting it earlier let `tseslint.configs.recommended` turn
   * `no-require-imports` back on.
   */
  {
    files: ['**/*.{js,cjs,mjs}', '**/*.config.{js,ts}', '**/jest.config.*'],
    languageOptions: { globals: { ...globals.node } },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      'no-undef': 'off',
    },
  },

  // ── API: NestJS, Node globals ───────────────────────────────
  {
    files: ['apps/api/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node, ...globals.jest },
      parserOptions: { sourceType: 'module' },
    },
    rules: {
      /**
       * Prisma's generated types are wide, and several services genuinely
       * need `any` at the query-builder boundary (`const where: any = {}`).
       * Warn so the count stays visible rather than pretending it is zero.
       */
      '@typescript-eslint/no-explicit-any': 'warn',

      /**
       * Error, not warn: an unused variable is how a redaction gets dropped.
       * The destructure-to-discard pattern this codebase uses for stripping
       * fields — `const { email: _email, ...rest } = user` — is exempted by
       * the underscore prefix, which is the point of the convention.
       */
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],

      // Nest resolves decorated constructor params at runtime; the base rule
      // cannot see that and reports them as unused.
      'no-unused-vars': 'off',
    },
  },

  // ── Web: Next.js ────────────────────────────────────────────
  //
  // The Next rules are registered twice on purpose. `compat.extends` pulls in
  // core-web-vitals (react, react-hooks, a11y); registering the plugin
  // directly is what makes `next build` recognise it. Without the second
  // block, `next build` runs its own lint pass with rules `npm run lint`
  // never sees — which is how a deploy breaks on an error nobody could
  // reproduce locally. It happened here: `no-html-link-for-pages` failed the
  // build while the standalone run reported nothing.
  ...compat.extends('next/core-web-vitals').map((config) => ({
    ...config,
    files: ['apps/web/**/*.{ts,tsx}'],
  })),
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { '@next/next': nextPlugin },
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
      'no-unused-vars': 'off',
      ...nextPlugin.configs.recommended.rules,
    },
  },

  // ── Tests ───────────────────────────────────────────────────
  {
    files: ['**/__tests__/**/*.ts', '**/*.spec.ts', '**/*.test.ts'],
    rules: {
      // Test doubles are cast freely and that is fine; the assertions are the
      // contract, not the shape of a mock.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
    },
  },
);
